---
image: "eu.gcr.io/campanda-docker/infra-elasticsearch"
imageTag: "7.15.0-002"
replicas: 3
esMajorVersion: 7
updateStrategy: OnDelete
imagePullSecrets:
  - name: docker-registry-google-eu

clusterName: "elasticsearch"
nodeGroup: "data"

roles:
  master: "false"
  data: "true"
  ingest: "false"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1000m"
    memory: "2Gi"

podAnnotations:
  app.kubernetes.io/name: es-cluster
  config.linkerd.io/skip-outbound-ports: "3306"
  linkerd.io/inject: enabled

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: pd-ssd
  resources:
    requests:
      storage: 30Gi

persistence:
  enabled: true
  annotations:
    volume.beta.kubernetes.io/storage-class: pd-ssd
